sudo: required
language: bash
services:
- docker
before_install:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install -y cf-cli
script:
  - docker build --file ops/compose/sustineri/Dockerfile -t emazzotta/sustineri:latest .
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; docker push emazzotta/sustineri:latest ; fi
  - cf login -a https://api.lyra-836.appcloud.swisscom.com -u "$CF_USERNAME" -p "$CF_PASSWORD"
  - cf push sustineri --docker-image emazzotta/sustineri

deploy:
  provider: cloudfoundry
  api: https://api.lyra-836.appcloud.swisscom.com
  username: mazzotta.emanuele@gmail.com
  password:
    secure: WXusIvd+VE4RlbkIfL3lHPgCHgXmjxs0Wzay1YODtF2Gpqz5IS5PCdSlbf1sqOTHpXyZIDBriUhaykYegsmpHWk75rR2gm7lfa2q/2rfTtmwWPF1Hohfei7HgC7E0MFE4hkQAkl0Q1IqF0jHj0JkH2HYKflW0mDYmWypV8/ezkbfkKWl+rbez4q+Sq2pWNy20G4T9QiC6JkvqiE+PvOkgZGj33plHxMrh+hCjbbCvoZOC6zSGfn6AQ1NDmRM5cjnhFzD7GOYoCjvu8AIiMPiVHOZ9D9ZFiV7SbOO9SNWcJo6TkZEtHzKy3h+QJ5z1YE9tR4nGziGxqMk8Qst10wvwzYop7ow38jOw4MEDsP5NEYvquu6X0oo7Pdzcfn/FzjMNcOHx6MklVd+H5OFiTLb3g0HnHMQn+5HOHKoVSYSEJ3pj3PaFcU1fnM4Tcx3yFYJBKO1FdwzJJbATF5INSnTa2lBGbO0KY5kuTeurpK/LjfRhMB9ris2CWK/kXXW5YvX3oUd2EVznnnv0wExO3wq6PJPFasG6lUGSYVt73kREqUfo7NZshW2tKpPXPDzIWO4OK7/YNifJs/WikilhyVKIzTpYnLowdM6ESIoXwqIH/P+Lu3za7VcEGtLzKTXtBaVIFxG5HA7QHrrIiOnTqfWqJKO4UpYl2WcTiGh1uVPABo=
  organization: hackzurich-mazzotta.emanuele@gmail.com
  space: ''
  on:
    repo: sustineri/sustineri
