sudo: required
language: bash
services:
- docker
before_install:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install -y cf-cli
script:
  - docker build --file ops/compose/sustineri/Dockerfile -t emazzotta/sustineri:latest .
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; docker push emazzotta/sustineri:latest ; fi
  - cf login -a https://api.lyra-836.appcloud.swisscom.com -u "$CF_USERNAME" -p "$CF_PASSWORD"
  - cf push -f ops/deploy/manifest-dev.yml
